### ISSUE TITLE
1-22-2015 doesnt work in latest safari

### ISSUE THREAD

**Issue by sury777** [tidwall/digitalrain#2]

**Comment by tidwall** [comment]
What version of Safari and MacOS are you using?

**Comment by sury777** [comment]
windows 7 
safari 5.1.7(7534.57.2)  no errors just black screen

**Comment by tidwall** [comment]
I won't be updating digital rain for Windows Safari.

Unfortunately Apple discontinued Windows Safari a few years ago. The browser is only version 6 (Mac and iOS are on version 8) and missing important functions needed to run the digital rain app.

**Comment by sury777** [comment]
good job anyway, bye now
