### ISSUE TITLE
Question about webasm

### ISSUE THREAD

**Issue by alexanelli** [tidwall/digitalrain#4]
Stumbled upon this while browsing stackoverflow.  The end result is incredible, great stuff. 

I was wondering it'd be possible to write similar code (or a similar project) using web assembly now that go has a compilation target for it?  Do you think it'd be easier or harder?  

Just curious and wanted to compliment you on the coolness factor 👍

**Comment by tidwall** [comment]
I'm glad to hear that you like the project. It was a ton of fun to make.

I haven't had a chance to play with webasm yet, so I can't say if it's more or less difficult than GopherJS. I hope to try it at some point in the near future.

Thanks!
